In [2]:
%timeit 2**10


5.63 ns ± 0.184 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [3]:
def cube(x):
    """
    return the cube of x.
    """
    return x ** 3

In [4]:
myList = ['Ali', 'amin', 3]

In [5]:
??myList

Type:        list
String form: ['Ali', 'amin', 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [6]:
??cube

Signature: cube(x)
Source:   
def cube(x):
    """
    return the cube of x.
    """
    return x ** 3
File:      /tmp/ipykernel_11442/1023039599.py
Type:      function

In [31]:
import numpy as np
np.__version__


'2.1.3'

In [8]:
np.array([1, 2, 3])


array([1, 2, 3])

In [9]:
np.array([[1, 2], [2, 3], [3, 4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [10]:
np.array([[['000', '001'], ['010', '011']], [['100', '101'], ['110', '111']]])

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3, 3, 3, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [13]:
np.ones((1, 100, 1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [14]:
np.full((2, 2), '#')

array([['#', '#'],
       ['#', '#']], dtype='<U1')

In [15]:
np.arange(0, 15, 4)

array([ 0,  4,  8, 12])

In [16]:
np.linspace(0, 2000, 5, )

array([   0.,  500., 1000., 1500., 2000.])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.empty(3)

array([0., 0., 0.])

In [19]:
np.random.random((3, 5))

array([[0.0437033 , 0.80572264, 0.98305778, 0.81655358, 0.00547561],
       [0.41842979, 0.9274166 , 0.30005985, 0.06925631, 0.26269808],
       [0.71662135, 0.855075  , 0.85111098, 0.56420306, 0.14492898]])

In [20]:
np.random.randint(0, 12, (2, 3, 6))

array([[[ 1,  8,  4,  7,  4, 10],
        [10,  6,  8,  6,  4,  7],
        [ 6,  1,  7,  4,  7,  5]],

       [[ 4,  8,  2,  7,  5,  7],
        [ 8,  0,  2, 11,  5,  8],
        [ 9,  2, 10,  9, 10,  1]]])

In [21]:
np.random.normal(0, 1)

0.707064234369896

In [22]:
np.full_like((3, 3), np.random.random())

array([0, 0])

In [23]:
np.astype(np.full_like(np.random.normal(0, 1, (4, 3)), 31), str)

array([['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0']], dtype='<U32')

In [24]:
a = np.full_like(np.random.normal(0, 1, (10, 10)), np.random.randint(1, 10))
np.array(a, int)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [25]:
a.shape

(10, 10)

In [26]:
a.nbytes


800

In [27]:
a.dtype

dtype('float64')

In [28]:
a[1]

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [29]:
a[0, 3]

np.float64(4.0)

In [30]:
print("amin")


amin
