In [3]:
%timeit 2**10

5.11 ns ± 0.125 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [9]:
def cube(x):
    """
    return the cube of x.
    """
    return x ** 3

In [6]:
myList = ['Ali', 'amin', 3]

In [11]:
??myList

Type:        list
String form: ['Ali', 'amin', 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [10]:
??cube

Signature: cube(x)
Source:   
def cube(x):
    """
    return the cube of x.
    """
    return x ** 3
File:      /tmp/ipykernel_6197/1023039599.py
Type:      function

In [2]:
import numpy as np
np.__version__


'2.1.3'

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
np.array([[1, 2], [2, 3], [3, 4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [9]:
np.array([[['000', '001'], ['010', '011']], [['100', '101'], ['110', '111']]])

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((1, 1))

array([[1.]])

In [15]:
np.full((2, 2), '#')

array([['#', '#'],
       ['#', '#']], dtype='<U1')

In [17]:
np.arange(0, 15, 4)

array([ 0,  4,  8, 12])

In [23]:
np.linspace(0, 2000, 50)

array([   0.        ,   40.81632653,   81.63265306,  122.44897959,
        163.26530612,  204.08163265,  244.89795918,  285.71428571,
        326.53061224,  367.34693878,  408.16326531,  448.97959184,
        489.79591837,  530.6122449 ,  571.42857143,  612.24489796,
        653.06122449,  693.87755102,  734.69387755,  775.51020408,
        816.32653061,  857.14285714,  897.95918367,  938.7755102 ,
        979.59183673, 1020.40816327, 1061.2244898 , 1102.04081633,
       1142.85714286, 1183.67346939, 1224.48979592, 1265.30612245,
       1306.12244898, 1346.93877551, 1387.75510204, 1428.57142857,
       1469.3877551 , 1510.20408163, 1551.02040816, 1591.83673469,
       1632.65306122, 1673.46938776, 1714.28571429, 1755.10204082,
       1795.91836735, 1836.73469388, 1877.55102041, 1918.36734694,
       1959.18367347, 2000.        ])

In [20]:
np.eye(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
np.empty(10000)

array([6.25725084e-310, 6.25725084e-310, 5.00550039e-310, ...,
       5.00550040e-310, 5.44954407e-321, 0.00000000e+000])

In [27]:
np.random.random(3)

array([0.59522854, 0.64805867, 0.5894743 ])

In [30]:
np.random.randint(0, 12, (2, 3))

array([[1, 1, 8],
       [6, 5, 2]])

In [32]:
np.random.normal(0, 1, (2, 3))

array([[ 0.3057443 ,  0.93970157,  0.11009533],
       [ 0.17742482, -2.55953842, -1.89506309]])

In [34]:
np.full_like(np.random.normal(0, 1, (4, 3)), 31)

array([[31., 31., 31.],
       [31., 31., 31.],
       [31., 31., 31.],
       [31., 31., 31.]])

In [41]:
np.astype(np.full_like(np.random.normal(0, 1, (4, 3)), 31), str)

array([['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0']], dtype='<U32')

In [55]:
a = np.full_like(np.random.normal(0, 1, (4, 3)), 31)
np.array(a, int)

array([[31, 31, 31],
       [31, 31, 31],
       [31, 31, 31],
       [31, 31, 31]])

In [56]:
a.shape


(4, 3)

In [59]:
a.nbytes


96