In [3]:
%timeit 2**10

5.11 ns ± 0.125 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [9]:
def cube(x):
    """
    return the cube of x.
    """
    return x ** 3

In [6]:
myList = ['Ali', 'amin', 3]

In [11]:
??myList

Type:        list
String form: ['Ali', 'amin', 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [10]:
??cube

Signature: cube(x)
Source:   
def cube(x):
    """
    return the cube of x.
    """
    return x ** 3
File:      /tmp/ipykernel_6197/1023039599.py
Type:      function

In [3]:
import numpy as np
np.__version__


'2.1.3'

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
np.array([[1, 2], [2, 3], [3, 4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [6]:
np.array([[['000', '001'], ['010', '011']], [['100', '101'], ['110', '111']]])

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3, 3, 3, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [12]:
np.ones((1, 1, 1))

array([[[1.]]])

In [15]:
np.full((2, 2), '#')

array([['#', '#'],
       ['#', '#']], dtype='<U1')

In [17]:
np.arange(0, 15, 4)

array([ 0,  4,  8, 12])

In [16]:
np.linspace(0, 2000, 5, )

array([   0.,  500., 1000., 1500., 2000.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.empty(3)

array([1., 1., 1.])

In [27]:
np.random.random(3)

array([0.59522854, 0.64805867, 0.5894743 ])

In [25]:
np.random.randint(0, 12, (2, 3, 6))

array([[[ 0, 10,  3,  6,  2,  7],
        [ 2,  0,  1, 11,  9,  9],
        [ 6,  5, 11,  8,  4,  2]],

       [[ 8,  9, 10,  6,  3,  1],
        [ 8,  4, 10,  2,  2,  0],
        [10,  1,  5, 11,  8,  6]]])

In [32]:
np.random.normal(0, 1, (2, 3))

array([[ 0.3057443 ,  0.93970157,  0.11009533],
       [ 0.17742482, -2.55953842, -1.89506309]])

In [34]:
np.full_like(np.random.normal(0, 1, (4, 3)), 31)

array([[31., 31., 31.],
       [31., 31., 31.],
       [31., 31., 31.],
       [31., 31., 31.]])

In [41]:
np.astype(np.full_like(np.random.normal(0, 1, (4, 3)), 31), str)

array([['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0'],
       ['31.0', '31.0', '31.0']], dtype='<U32')

In [32]:
a = np.full_like(np.random.normal(0, 1, (10, 10)), np.random.randint(1, 10))
np.array(a, int)

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [33]:
a.shape

(10, 10)

In [34]:
a.nbytes

800

In [38]:
a.dtype

dtype('float64')

In [40]:
a[1]

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [43]:
a[0, 3]

np.float64(6.0)