In [2]:
import numpy as np
np.__version__

'2.1.3'

In [3]:
a =  np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
np.array([[1, 2],
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.zeros(3)
np.zeros((2,  3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 3, 4), tuple)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=object)

In [7]:
np.full((3, 4), '01')

array([['01', '01', '01', '01'],
       ['01', '01', '01', '01'],
       ['01', '01', '01', '01']], dtype='<U2')

In [8]:
np.arange(0, 150, 4)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148])

In [9]:
np.linspace(0,  15, 12)

array([ 0.        ,  1.36363636,  2.72727273,  4.09090909,  5.45454545,
        6.81818182,  8.18181818,  9.54545455, 10.90909091, 12.27272727,
       13.63636364, 15.        ])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.random.random((5, 1))

array([[0.10493518],
       [0.72171382],
       [0.10779943],
       [0.67081013],
       [0.74738136]])

In [13]:
np.random.randint(0,  19, (2, 4))

array([[ 9, 17,  8, 18],
       [13, 14,  4, 11]])

In [14]:
np.random.normal(0, 1, (2, 3))

array([[ 1.82568067,  0.88284305, -0.06003697],
       [ 0.67581594,  0.29300146,  2.71592288]])

In [15]:
a  = np.random.randint(0, 10, (2, 3))

In [16]:
np.full_like(a, 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [17]:
np.array([False, True], dtype='int_')

array([0, 1])

In [18]:
np.array([1, 0, 3.14], dtype='bool_')

array([ True, False,  True])

In [19]:
np.array([2.71828182845, 3.14159265359], dtype='int')

array([2, 3])

In [20]:
np.array([255], dtype='uint8')

array([255], dtype=uint8)

In [26]:
np.array(['hello', 'world'], dtype='str_')

array(['hello', 'world'], dtype='<U5')

In [40]:
a = np.array([[1, 2],
          [3, 4],
          [5, 6]], dtype='float32')

In [77]:
print(a)
print(a.ndim, a.shape, a.dtype)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2 (4, 3) int64


In [78]:
print(a.itemsize, a.nbytes)

8 96


In [80]:
print(a[2:0, 2, 1])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [66]:
print(a)

[[ 1.  2.]
 [30.  4.]
 [ 5.  6.]]


In [67]:
a = np.array([0, 1, 2, 3, 4, 5])

In [68]:
print(a[:3])

[0 1 2]


In [69]:
print(a[2:4])

[2 3]


In [70]:
print(a[1:5:2])

[1 3]


In [71]:
print(a[::-1])

[5 4 3 2 1 0]


In [72]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])

In [81]:
print(a[:2, 1:])

[[1 2]
 [4 5]]
