In [4]:
import numpy as np
np.__version__

'2.1.3'

In [6]:
a =  np.array([1, 2, 3])
a

array([1, 2, 3])

In [9]:
np.array([[1, 2],
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.zeros(3)
np.zeros((2,  3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2, 3, 4), tuple)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=object)

In [17]:
np.full((3, 4), '01')

array([['01', '01', '01', '01'],
       ['01', '01', '01', '01'],
       ['01', '01', '01', '01']], dtype='<U2')

In [20]:
np.arange(0, 150, 4)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148])

In [27]:
np.linspace(0,  15, 12)

array([ 0.        ,  1.36363636,  2.72727273,  4.09090909,  5.45454545,
        6.81818182,  8.18181818,  9.54545455, 10.90909091, 12.27272727,
       13.63636364, 15.        ])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.random.random((5, 1))

array([[0.09185641],
       [0.28472148],
       [0.8865072 ],
       [0.01628953],
       [0.51345193]])

In [34]:
np.random.randint(0,  19, (2, 4))

array([[10, 16,  3,  2],
       [10, 18, 18,  0]])

In [35]:
np.random.normal(0, 1, (2, 3))

array([[ 0.6888418 , -0.23788134,  1.83203802],
       [-0.26043224, -0.62055325, -0.57489118]])

In [37]:
a  = np.random.randint(0, 10, (2, 3))

In [40]:
np.full_like(a, 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.array()