In [76]:
import numpy as np
np.__version__

'2.1.3'

In [77]:
a =  np.array([1, 2, 3])
a

array([1, 2, 3])

In [78]:
np.array([[1, 2],
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
np.zeros(3)
np.zeros((2,  3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((2, 3, 4), tuple)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=object)

In [81]:
np.full((3, 4), '01')

array([['01', '01', '01', '01'],
       ['01', '01', '01', '01'],
       ['01', '01', '01', '01']], dtype='<U2')

In [82]:
np.arange(0, 150, 4)

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148])

In [83]:
np.linspace(0,  15, 12)

array([ 0.        ,  1.36363636,  2.72727273,  4.09090909,  5.45454545,
        6.81818182,  8.18181818,  9.54545455, 10.90909091, 12.27272727,
       13.63636364, 15.        ])

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [86]:
np.random.random((5, 1))

array([[0.66734141],
       [0.42707644],
       [0.60449335],
       [0.44511352],
       [0.93857309]])

In [87]:
np.random.randint(0,  19, (2, 4))

array([[ 5,  4,  6,  4],
       [ 9,  7, 11,  2]])

In [88]:
np.random.normal(0, 1, (2, 3))

array([[ 0.85115886, -0.32967833,  1.08673762],
       [-1.52880363,  0.61840003, -0.24079912]])

In [89]:
a  = np.random.randint(0, 10, (2, 3))

In [90]:
np.full_like(a, 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [91]:
np.array([False, True], dtype='int_')

array([0, 1])

In [92]:
np.array([1, 0, 3.14], dtype='bool_')

array([ True, False,  True])

In [93]:
np.array([2.71828182845, 3.14159265359], dtype='int')

array([2, 3])

In [94]:
np.array([255], dtype='uint8')

array([255], dtype=uint8)

In [95]:
np.array(['hello', 'world'], dtype='str_')

array(['hello', 'world'], dtype='<U5')

In [96]:
a = np.array([[1, 2],
          [3, 4],
          [5, 6]], dtype='float32')

In [97]:
print(a)
print(a.ndim, a.shape, a.dtype)


[[1. 2.]
 [3. 4.]
 [5. 6.]]
2 (3, 2) float32


In [98]:
print(a.itemsize, a.nbytes)

4 24


In [99]:
print(a[2:0, 2, 1])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [66]:
print(a)

[[ 1.  2.]
 [30.  4.]
 [ 5.  6.]]


In [67]:
a = np.array([0, 1, 2, 3, 4, 5])

In [68]:
print(a[:3])

[0 1 2]


In [69]:
print(a[2:4])

[2 3]


In [70]:
print(a[1:5:2])

[1 3]


In [71]:
print(a[::-1])

[5 4 3 2 1 0]


In [72]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])

In [81]:
print(a[:2, 1:])

[[1 2]
 [4 5]]


In [83]:
print(a[1:3, ::2])
print(a[2, :])

[[3 5]
 [6 8]]
[6 7 8]


In [137]:
a = np.random.randint(0, 10, (3, 5))
print(a)
print(a[0:5, 3:5])

[[7 3 0 1 7]
 [7 0 6 6 5]
 [8 7 4 1 6]]
[[1 7]
 [6 5]
 [1 6]]


In [138]:
a[2, 3] = 3.14

In [139]:
print(a)

[[7 3 0 1 7]
 [7 0 6 6 5]
 [8 7 4 3 6]]


In [140]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [149]:
sub_copy_a = a[2:4, 1:].copy()
print(sub_copy_a)
sub_copy_a[0, 0] = 10
print(sub_copy_a, "\n\n", a)

[[7 8]]
[[10  8]] 

 [[0 1 2]
 [3 4 5]
 [6 7 8]]
