In [2]:
import numpy as np

In [3]:
a = np.arange(8).reshape(2, 4)
a
a.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [4]:
print(a.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [5]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
a.transpose(1, 2, 0)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [7]:
a.swapaxes(0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [11]:
x = np.arange(6).reshape(2, 3)
y = np.arange(6, 12).reshape(2, 3)
z = np.arange(12, 15).reshape(1, 3)
np.concatenate([x, y, z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [12]:
np.concat([x, y], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [21]:
a = np.arange(116)
x, y, z = np.split(a, [15, 50])

In [22]:
print(x, y, z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49] [ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115]


In [35]:
a = np.arange(12).reshape(2, 6)
print(a)
x, y, z = np.split(a, 2, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [33]:
print(x)
print(y)

[[0 1 2]
 [6 7 8]]
[[ 3  4  5]
 [ 9 10 11]]
