In [2]:
import numpy as np

In [10]:
a = np.arange(8).reshape(2, 4)
a
a.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [6]:
print(a.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [13]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
a.transpose(1, 2, 0)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [16]:
a.swapaxes(0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [26]:
x = np.arange(6).reshape(2, 3)
y = np.arange(6, 12).reshape(2, 3)
z = np.arange(12, 15).reshape(1, 3)
np.concat([x, y, z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
np.concat([x, y], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])