In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])

In [15]:
arr = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[1:5]

array([2, 3, 4, 5])

In [21]:
print(arr[2:])

[3 4 5 6 7 8 9]


In [30]:
arr[5::-1]


array([6, 5, 4, 3, 2, 1])

In [32]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [33]:
sub_copy_a = a[2:4, 1:].copy()

In [34]:
sub_copy_a

array([[7, 8]])

In [35]:
sub_copy_a[0, 0] = 10

In [36]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
sub_copy_a

array([[10,  8]])

In [44]:
print(a.reshape(1, 9))

[[0 1 2 3 4 5 6 7 8]]


In [51]:
b = a[0:1, 4:]
b

array([], shape=(1, 0), dtype=int64)

In [66]:
a = np.arange(16)
a = a.reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
a.faltten()

AttributeError: 'numpy.ndarray' object has no attribute 'faltten'