In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])

In [5]:
a

array([0, 1, 2, 3])

In [6]:
print(a[0])

0


In [16]:
a = np.random.randint(0, 10, (3, 5, 4))


In [17]:
print(a)

[[[8 7 5 6]
  [1 7 1 8]
  [7 2 9 6]
  [7 7 5 3]
  [8 7 7 9]]

 [[5 6 7 1]
  [4 8 2 7]
  [0 8 7 0]
  [2 3 7 8]
  [7 7 5 3]]

 [[0 7 6 5]
  [9 9 0 1]
  [0 8 5 9]
  [1 5 3 9]
  [4 8 6 1]]]


In [18]:
print(a[2, 3])

[1 5 3 9]


In [21]:
a[2, 3] = 90.90

In [22]:
print(a)

[[[ 8  7  5  6]
  [ 1  7  1  8]
  [ 7  2  9  6]
  [ 7  7  5  3]
  [ 8  7  7  9]]

 [[ 5  6  7  1]
  [ 4  8  2  7]
  [ 0  8  7  0]
  [ 2  3  7  8]
  [ 7  7  5  3]]

 [[ 0  7  6  5]
  [ 9  9  0  1]
  [ 0  8  5  9]
  [90 90 90 90]
  [ 4  8  6  1]]]
