In [5]:
import numpy as np

In [6]:
a = np.array([0, 1, 2, 3])

In [7]:
arr = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[1:5]

array([2, 3, 4, 5])

In [9]:
print(arr[2:])

[3 4 5 6 7 8 9]


In [10]:
arr[5::-1]


array([6, 5, 4, 3, 2, 1])

In [11]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [12]:
sub_copy_a = a[2:4, 1:].copy()

In [13]:
sub_copy_a

array([[7, 8]])

In [14]:
sub_copy_a[0, 0] = 10

In [15]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
sub_copy_a

array([[10,  8]])

In [17]:
print(a.reshape(1, 9))

[[0 1 2 3 4 5 6 7 8]]


In [18]:
b = a[0:1, 4:]
b

array([], shape=(1, 0), dtype=int64)

In [19]:
a = np.arange(16)
a = a.reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])