In [13]:
import numpy as np

a = np.random.randint(0, 100, 50)
b = np.random.randint(0, 100, 50)
print(a, b)


[41 31 60  8 23 27 57 71 26  3 40 78  1  5 65 47 22 69 59 47 64 40 29 50
 18 14 72 44 98 86 38 84 58 41 79 93 59  2 74  2 15 16 18 90 41 13 51 33
  2 94] [14 43 50 82 46 99 11 46 49 28 90 47 11 33  5 52 41 73 27  3 71 41  8 89
 53 34 25 69 98 30 56 21  1 21 88 71 47  6 22 61 32 93 44 42 35 69 52 90
 99 91]


In [14]:
c = np.add(a, b)
print(c)

[ 55  74 110  90  69 126  68 117  75  31 130 125  12  38  70  99  63 142
  86  50 135  81  37 139  71  48  97 113 196 116  94 105  59  62 167 164
 106   8  96  63  47 109  62 132  76  82 103 123 101 185]


In [15]:
c = a + b
print(c)

[ 55  74 110  90  69 126  68 117  75  31 130 125  12  38  70  99  63 142
  86  50 135  81  37 139  71  48  97 113 196 116  94 105  59  62 167 164
 106   8  96  63  47 109  62 132  76  82 103 123 101 185]


In [16]:
c = np.subtract(a, b)
print(c, "\n")
c = a - b
print(c)

[ 27 -12  10 -74 -23 -72  46  25 -23 -25 -50  31 -10 -28  60  -5 -19  -4
  32  44  -7  -1  21 -39 -35 -20  47 -25   0  56 -18  63  57  20  -9  22
  12  -4  52 -59 -17 -77 -26  48   6 -56  -1 -57 -97   3] 

[ 27 -12  10 -74 -23 -72  46  25 -23 -25 -50  31 -10 -28  60  -5 -19  -4
  32  44  -7  -1  21 -39 -35 -20  47 -25   0  56 -18  63  57  20  -9  22
  12  -4  52 -59 -17 -77 -26  48   6 -56  -1 -57 -97   3]


In [17]:
c = np.multiply(a, b)
print(c, "\n")
c = a * b
print(c)

[ 574 1333 3000  656 1058 2673  627 3266 1274   84 3600 3666   11  165
  325 2444  902 5037 1593  141 4544 1640  232 4450  954  476 1800 3036
 9604 2580 2128 1764   58  861 6952 6603 2773   12 1628  122  480 1488
  792 3780 1435  897 2652 2970  198 8554] 

[ 574 1333 3000  656 1058 2673  627 3266 1274   84 3600 3666   11  165
  325 2444  902 5037 1593  141 4544 1640  232 4450  954  476 1800 3036
 9604 2580 2128 1764   58  861 6952 6603 2773   12 1628  122  480 1488
  792 3780 1435  897 2652 2970  198 8554]


In [18]:
c = np.divide(a, b)
print(c, "\n")
c = a / b
print(c)

[2.92857143e+00 7.20930233e-01 1.20000000e+00 9.75609756e-02
 5.00000000e-01 2.72727273e-01 5.18181818e+00 1.54347826e+00
 5.30612245e-01 1.07142857e-01 4.44444444e-01 1.65957447e+00
 9.09090909e-02 1.51515152e-01 1.30000000e+01 9.03846154e-01
 5.36585366e-01 9.45205479e-01 2.18518519e+00 1.56666667e+01
 9.01408451e-01 9.75609756e-01 3.62500000e+00 5.61797753e-01
 3.39622642e-01 4.11764706e-01 2.88000000e+00 6.37681159e-01
 1.00000000e+00 2.86666667e+00 6.78571429e-01 4.00000000e+00
 5.80000000e+01 1.95238095e+00 8.97727273e-01 1.30985915e+00
 1.25531915e+00 3.33333333e-01 3.36363636e+00 3.27868852e-02
 4.68750000e-01 1.72043011e-01 4.09090909e-01 2.14285714e+00
 1.17142857e+00 1.88405797e-01 9.80769231e-01 3.66666667e-01
 2.02020202e-02 1.03296703e+00] 

[2.92857143e+00 7.20930233e-01 1.20000000e+00 9.75609756e-02
 5.00000000e-01 2.72727273e-01 5.18181818e+00 1.54347826e+00
 5.30612245e-01 1.07142857e-01 4.44444444e-01 1.65957447e+00
 9.09090909e-02 1.51515152e-01 1.30000000e+01 9.038

In [27]:
index = np.random.randint(-10, 10, 5)
index

array([ -8,  -2,   6, -10,  -4])

[ 8  2  6 10  4] 
 [       nan        nan 2.44948974        nan        nan] 
 [ 64   4  36 100  16] 
 [False False False False False]


/tmp/ipykernel_16767/920654753.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.abs(index), "\n", np.sqrt(index), "\n", np.square(index), "\n", np.isnan(index))


In [29]:
np.isnan(index)

array([False, False, False, False, False])

In [30]:
np.square(index)

array([ 64,   4,  36, 100,  16])

In [31]:
np.sqrt(index)

/tmp/ipykernel_16767/210181419.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(index)


array([       nan,        nan, 2.44948974,        nan,        nan])

In [37]:
a = np.abs(index)
a.sort()

In [38]:
a

array([ 2,  4,  6,  8, 10])